### PR TITLE
Add Mashape API support

### PR DESCRIPTION
**Pull request by rm-you**
Add support for using the Mashape API endpoint

### CODE REVIEW

**Comment by rm-you** [comment]
Hey, it would be awesome to have this upstream, have you had a chance to take a look?
Obviously I'm biased, but I think it is useful functionality! :)

**Comment by Damgaard** [comment]
Hey, this commit but it needs 2 small things before I can merge.

 - An entry in the changelog file. This is a new feature that and it's worth notifying people about.
 - One or more link in the new documentation to where more information can be found about mashable, pricing structure and how to get an API key.

Once I have those two things I'll merge it and roll out a new version quickly after.

**Comment by rm-you** [comment]
Done!

**Comment by rm-you** [comment]
Ah, conflicts. Fixing.

**Comment by Damgaard** [comment]
Pyimgur 0.6.0 has just been released which includes your PR.

Thanks a lot for your contribution.

**Comment by megies** [comment]
@Damgaard I think it'd be good to also tag all releases here on github.. easier to keep an overview that way (in this case that measns the 0.6.0)

**Comment by megies** [comment]
Oh and it seems the init py still has 0.5.3 as version.. https://github.com/Damgaard/PyImgur/blob/master/pyimgur/__init__.py#L49

**Comment by megies** [comment]
Euhm.. but it's correct in the pypi package, I'm confused now ;-)

**Pull request merged**
